services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-video
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=America/New_York
      - N8N_ALLOW_LOCAL_FILE_TRIGGER=true
      - N8N_ALLOW_EXECUTE_COMMAND=true 
      - N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES:false
      - N8N_ENABLE_NODE_DEV=true
      - NODES_EXCLUDE=[]
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      
    volumes:
      - n8n_data:/home/node/.n8n

    mem_limit: 16g
    mem_reservation: 4g

volumes:
  n8n_data:
