# n8n Configuration
N8N_MAX_PAYLOAD_SIZE=1024000
NODE_OPTIONS=--max-old-space-size=6144
EXECUTIONS_DATA_MAX_TTL=0
EXECUTIONS_DATA_PRUNE=false
EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
EXECUTIONS_DATA_SAVE_ON_ERROR=all

# Database (use SQLite for simplicity)
DB_TYPE=sqlite
DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite

# File Handling
N8N_DEFAULT_BINARY_DATA_MODE=filesystem
N8N_PERSISTED_BINARY_DATA_TTL=172800
N8N_PERSISTED_BINARY_DATA_MAX_SIZE=10737418240

# Security
N8N_SECURE_COOKIE=false
N8N_ENCRYPTION_KEY=your-secure-key-here-change-this

# Video Processing Variables
VIDEO_CHUNK_SIZE_MB=100
VIDEO_TEMP_DIR=/data/videos/temp
MAX_CONCURRENT_PROCESSES=2
FFMPEG_THREADS=4

# Logging
N8N_LOG_LEVEL=info
N8N_LOG_OUTPUT=console

# Telemetry (optional - disable for privacy)
N8N_DIAGNOSTICS_ENABLED=false
N8N_METRICS=false
N8N_VERSION_NOTIFICATIONS_ENABLED=false